### ISSUE TITLE
pngがexportできないときがある？

### ISSUE THREAD

**Issue by Tnoriaki** [kindsenior/log_plotter#99]
```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/pyqtgraph/exporters/Exporter.py", line 77, in fileSaveFinished
    self.export(fileName=fileName, **self.fileDialog.opts)
  File "/usr/local/lib/python2.7/dist-packages/pyqtgraph/exporters/ImageExporter.py", line 71, in export
    bg = np.empty((self.params['width'], self.params['height'], 4), dtype=np.ubyte)
TypeError: 'float' object cannot be interpreted as an index
```
というエラーが出てpngがexport出来ない時があるのですが誰か心当たりありますでしょうか？

簡易的な解決策はpyqtgraphのソースコードを
https://groups.google.com/forum/#!topic/pyqtgraph/4jiAPUpLpF4
と書き換えるとできるのですが，
そもそもwidthとheightがintじゃないのが問題でおかしい気もしますが
よくわからないです．．．

**Comment by Tnoriaki** [comment]
pyqtgraphにissueがすでに上がっているようなのでcloseします.
https://github.com/pyqtgraph/pyqtgraph/issues/454
